version: "3"

services:
  web:
    build: ./web_service
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    networks:
      software_dev:
        ipv4_address: 10.10.50.10

  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      software_dev:
        ipv4_address: 10.10.50.20

networks:
  software_dev:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
